//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> idCategory { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> timePublished { get; set; }
        public string nameUnit { get; set; }
        public string url { get; set; }
    }
}
