//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMenu
    {
        public int id { get; set; }
        public int idMenu { get; set; }
        public string title { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<int> idComponent { get; set; }
        public string url { get; set; }
    }
}
