//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public Nullable<int> idCategory { get; set; }
        public string idUserCreated { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string content { get; set; }
        public string description { get; set; }
        public bool published { get; set; }
        public Nullable<System.DateTime> timePublished { get; set; }
        public string image { get; set; }
        public string tags { get; set; }
        public int version { get; set; }
        public bool featured { get; set; }
        public string metaDescription { get; set; }
        public string metaKewords { get; set; }
        public string author { get; set; }
        public string robots { get; set; }
        public string imageBanner { get; set; }
        public string colorBackgroundBanner { get; set; }
        public string colorTitleBanner { get; set; }
        public string colorTextBanner { get; set; }
        public string note { get; set; }
        public string maSanPham { get; set; }
        public string congsuatThietKe { get; set; }
        public string chukyTaoHinh { get; set; }
        public string congsuatDien { get; set; }
        public string cocheRungEp { get; set; }
        public string khayDoGach { get; set; }
        public string baohanh { get; set; }
        public string sanxuatTai { get; set; }
        public string nhansu { get; set; }
        public string dientichNhaMay { get; set; }
        public string congnhanLaiMay { get; set; }
        public string congnhanSanXuat { get; set; }
        public string congnhanBocXep { get; set; }
        public string nhaxuongDatMay { get; set; }
        public string khuvucPhoiGachNon { get; set; }
        public string baichuaThanhPham { get; set; }
        public string baichuaNguyenLieu { get; set; }
        public string congtrinhkhac { get; set; }
        public string tailieuKyThuat { get; set; }
        public string kichthuoc { get; set; }
        public string khoiluong { get; set; }
        public string sovien { get; set; }
        public string cuongdonen { get; set; }
        public string dohutnuoc { get; set; }
        public string khoiluongTheTich { get; set; }
        public string dorong { get; set; }
        public string thongsoKyThuat { get; set; }
        public string banve2d { get; set; }
        public string banve3d { get; set; }
        public string nangsuatTronTinhToan { get; set; }
        public string nangsuatTronThucTe { get; set; }
        public string dungtichMeTron { get; set; }
        public string chieucaoXaLieu { get; set; }
        public string hethongDieuKhien { get; set; }
        public string kieucoiTron { get; set; }
        public string dungtichCoiTron { get; set; }
        public string dungtichPheuChua { get; set; }
        public string capcotlieu { get; set; }
        public string vittaiCapXiMang { get; set; }
        public string tongcongsuatTieuThuDien { get; set; }
        public string hinhanh1 { get; set; }
        public string hinhanh2 { get; set; }
        public string hinhanh3 { get; set; }
        public string hinhanh4 { get; set; }
        public string hinhanh5 { get; set; }
        public string hinhanh6 { get; set; }
    }
}
